spring:
  application:
    name: automatewizard
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db
    driver-class-name: org.h2.Driver
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update #create-drop, create, update, validate, none
    show-sql: true
    properties:
      format_sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080
  forward-headers-strategy: framework
token:
  signing:
    key: aS1rbm93LWl0LWlzLWJhZC10by1rZWVwLXRoZS1rZXktaW4tdGhlLXB1YmxpYy1kb21haW4tYnV0LWl0LWlzLWEtcHJvdG90eXBlLXNvLWl0LWlzLW9r